### PR TITLE
Sending function updates and Json edits

### PR DESCRIPTION
**Pull request by Kevinizevbigie**
Great library friend. I made the following updates: 

- moved the "from" json field from the "personalisations" to the toplevel json
- added a from-name for email sending so the user can add customised names depending on the email type. My previous company was an email marketing business. We sent over 1m emails on behalf of clients. This is good practice.
- changed "from" to "from-email"
- Updated docs - example send function with mandatory keys for sending
- Updated docs - told user all mandatory fields

Let me know if any changes should be made.

### CODE REVIEW

**Comment by vindarel** [comment]
Hello, thanks for taking a shot at improving a Lisp library! 

I have the concern that you removed the :from field, breaking backwards compatibility. I like Lisp libraries' stability. The from-name addition is much welcome though. You could leave the existing :from field and add a warning if it is used, saying it's deprecated and should be updated.

We have :reply-to using an alist:

                         :reply-to '(("email" . "noreply@example.com") ("name" . "No Reply"))

maybe :from should be changed to look like it? (and, to no break backwards compatibility, check if it is a string or an alist)

**Comment by Kevinizevbigie** [comment]
Yes, I agree regarding backwards compatibility. Will make the changes and resubmit

**Comment by Kevinizevbigie** [comment]
Regarding the `from` field, if we turn that into the same format as `reply-to`, then then user will need to pass an a-list. I suggested keeping inputs simple (on the eyes, and for input with this:

```lisp
 `(("from" ("email" . ,from)
       ("name" . ,from-name)))
```
This block makes it clear what the sendgrid-json will produce.

I did change the `from-email` back to from because with the addition of from-name, its clear what it is.

Thoughts?

**Comment by vindarel** [comment]
Hi, sorry for the late reply. I have only one hard thought, to not break backwards compatibility.

You are right to keep the inputs simple \+1

thanks again for developing the lib.

**Pull request closed without merging**
